module.exports = {
  HtmlWebpackPlugin: [{
    filename: 'event-live.html',
    template: '_shared/layout.ejs',
    action: '賽事',
    description: '',
    chunks: ['event-live']
  }, {
    filename: 'event-today.html',
    template: '_shared/layout.ejs',
    action: '賽事',
    description: '',
    chunks: ['event-today']
  }, {
    filename: 'event-today-league.html',
    template: '_shared/layout.ejs',
    action: '联赛筛选',
    description: '',
    chunks: ['event-today-league']
  }, {
    filename: 'event-favorite.html',
    template: '_shared/layout.ejs',
    action: '賽事',
    description: '',
    chunks: ['event-favorite']
  }, {
    filename: 'event-early-market.html',
    template: '_shared/layout.ejs',
    action: '早盤',
    description: '',
    chunks: ['event-early-market']
  }, {
    filename: 'event-champion.html',
    template: '_shared/layout.ejs',
    action: '冠軍',
    description: '',
    chunks: ['event-champion']
  }]
};
